spring:
    application:
        name: minibank

telegram:
    bot:
        name: GpbBot
        token: ${bot_token}

services:
    middle:
        register:
            url: http://localhost:8081/api/v2/users
        create-account:
            url: http://localhost:8081/api/v2/users/{id}/accounts
        current-balance:
            url: http://localhost:8081/api/v2/users/{id}/accounts
        transfer:
            url: http://localhost:8081/api/v2/transfers
custom:
    timeout:
        connect: 5000
        read: 5000

server:
    port: 8080